name: Thau API

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Thau API
      run: |
        cd thau-api
        MVN_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        if [[ "$MVN_VERSION" == *"-SNAPSHOT" ]]; then
          >&2 echo "Project version is SNAPSHOT!" 
          exit 1
        fi

        ./mvnw clean verify

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: |
        cd thau-api

        ./mvnw package -Dmaven.test.skip=true

        MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

        echo "LOGIN TO DOCKER HUB"
        docker login -u mgrin -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        echo "BUILDING THE IMAGE"
        docker build --tag mgrin/thau:${MVN_VERSION} --tag mgrin/thau:latest .

        echo "PUSHING THE IMAGE"
        docker push mgrin/thau:latest